In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('qs-world-rankings-2025.csv')
df.head(10)

,2025 Rank,2024 Rank,Institution Name,Location,Location Full,Size,Academic Reputation,Employer Reputation,Faculty Student,Citations per Faculty,International Faculty,International Students,International Research Network,Employment Outcomes,Sustainability,QS Overall Score
0,1,1,Massachusetts Institute of Technology (MIT),US,United States,M,100.0,100.0,100.0,100.0,99.3,86.8,96.0,100.0,99.0,100
1,2,6,Imperial College London,UK,United Kingdom,L,98.5,99.5,98.2,93.9,100.0,99.6,97.4,93.4,99.7,98.5
2,3,3,University of Oxford,UK,United Kingdom,L,100.0,100.0,100.0,84.8,98.1,97.7,100.0,100.0,85.0,96.9
3,4,4,Harvard University,US,United States,L,100.0,100.0,96.3,100.0,74.1,69.0,99.6,100.0,84.4,96.8
4,5,2,University of Cambridge,UK,United Kingdom,L,100.0,100.0,100.0,84.6,100.0,94.8,99.3,100.0,84.8,96.7
5,6,5,Stanford University,US,United States,L,100.0,100.0,100.0,99.0,70.3,60.8,96.8,100.0,81.2,96.1
6,7,7,ETH Zurich - Swiss Federal Institute of Techno...,CH,Switzerland,L,98.8,87.2,65.9,97.9,100.0,98.6,95.7,90.5,98.8,93.9
7,8,8,National University of Singapore (NUS),SG,Singapore,XL,99.5,91.1,68.8,93.1,100.0,88.9,91.6,100.0,97.7,93.7
8,9,9,UCL,UK,United Kingdom,XL,99.5,98.3,95.9,72.2,99.0,100.0,99.9,70.3,74.8,91.6
9,10,15,California Institute of Technology (Caltech),US,United States,S,96.5,95.3,100.0,100.0,100.0,79.8,65.5,31.0,62.5,90.9

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1503 entries, 0 to 1502
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   2025 Rank                       1503 non-null   object
 1   2024 Rank                       1482 non-null   object
 2   Institution Name                1503 non-null   object
 3   Location                        1503 non-null   object
 4   Location Full                   1503 non-null   object
 5   Size                            1503 non-null   object
 6   Academic Reputation             1503 non-null   float64
 7   Employer Reputation             1503 non-null   float64
 8   Faculty Student                 1503 non-null   float64
 9   Citations per Faculty           1503 non-null   float64
 10  International Faculty           1403 non-null   float64
 11  International Students          1445 non-null   float64
 12  International Research Network  1502 non-null   float64
 13  Employment Outcomes             1503 non-null   float64
 14  Sustainability                  1484 non-null   float64
 15  QS Overall Score                1503 non-null   object
dtypes: float64(9), object(7)
memory usage: 188.0+ KB

In [5]:
df.describe()

,Academic Reputation,Employer Reputation,Faculty Student,Citations per Faculty,International Faculty,International Students,International Research Network,Employment Outcomes,Sustainability
count,1503.00000,1503.000000,1503.000000,1503.000000,1403.000000,1445.000000,1502.000000,1503.000000,1484.000000
mean,20.28656,19.786693,28.128676,23.503460,30.725374,25.580346,50.129095,23.825083,24.309299
std,22.32623,23.784986,27.613017,27.870692,34.328935,31.098689,29.866588,27.351315,31.074718
min,1.30000,1.100000,1.000000,1.000000,1.000000,1.000000,1.000000,1.200000,1.000000
25%,6.30000,4.300000,7.300000,2.800000,4.200000,2.900000,22.725000,4.000000,1.300000
50%,11.00000,9.400000,16.000000,9.900000,12.500000,9.600000,51.100000,11.800000,6.750000
75%,23.50000,25.300000,40.400000,36.400000,51.600000,38.300000,77.100000,33.400000,39.500000
max,100.00000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000

In [6]:
df.drop(df.index[:500], inplace=True)

In [9]:
df['2025 Rank'] = df['2025 Rank'].str.extract(r'(\d{3})')
df['2024 Rank'] = df['2024 Rank'].str.extract(r'(\d{3})')

In [15]:
df['2025 Rank'] = pd.to_numeric(df['2025 Rank'].str.replace("+", " "))
df['2024 Rank'] = pd.to_numeric(df['2024 Rank'].str.replace("+", " "))
df['QS Overall Score'] = pd.to_numeric(df['QS Overall Score'].str.replace(",", " "))

AttributeError: Can only use .str accessor with string values!